
name: Parse tag name test
on:
  push:
    tags:
      - 'vz*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 18.13

      - name: Get tag name
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          NEW_VERSION="v${VERSION}"
          node -p "let pkg=require('./package.json'); pkg.version='$NEW_VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Print package.json
        run: cat package.json

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run build:linux

      - name: Print folder structure
        run: ls -R

      - name: Archive Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux-built
          path: ./dist/MEDomicsLab-${GITHUB_REF/refs\/tags\//}-linux.deb

  