
name: Parse tag name test
on:
  push:
    tags:
      - 'vz*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 18.13
            
      - name: Get tag name
        shell: bash
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          NEW_VERSION="v${VERSION}"
          node -p "let pkg=require('./package.json'); pkg.version='$NEW_VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
        
      - name: Print package.json
        run: Get-Content package.json
            
      - name: Install dependencies
        run: npm install
            

      - name: Build for Windows
        run: npm run build:win

      - name: Print folder structure
        run: ls -R
        
      - name: Archive Windows 
        uses: actions/upload-artifact@v3
        with:
          name: windows-built
          path: ./dist/MEDomicsLab-${GITHUB_REF/refs\/tags\//}-win.exe
        
  