
name: Versioning
on:
  push:
    tags:
      - '*'
jobs:
  
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 18.13
                  
      - name: Install dependencies
        run: npm install

      - name: Get tag name
        run: echo ::set-env name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      

      - name: Overwrite version in package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${GITHUB_REF/refs\/tags\//}\"/g" package.json
          cat package.json

      - name: Print package.json
        run: cat package.json


  